// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity_review.proto

package cfwf_micro_service_activity_review

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//通用rpc调用返回结果
type RPC_CALL_RESULT int32

const (
	RPC_CALL_RESULT_RPC_CALL_RESULT_NONE        RPC_CALL_RESULT = 0
	RPC_CALL_RESULT_RPC_CALL_RESULT_SUCCESS     RPC_CALL_RESULT = 1
	RPC_CALL_RESULT_RPC_CALL_RESULT_DB_ERROR    RPC_CALL_RESULT = 2
	RPC_CALL_RESULT_RPC_CALL_RESULT_INPUT_ERROR RPC_CALL_RESULT = 3
	RPC_CALL_RESULT_RPC_CALL_RESULT_ERROR       RPC_CALL_RESULT = 4
)

var RPC_CALL_RESULT_name = map[int32]string{
	0: "RPC_CALL_RESULT_NONE",
	1: "RPC_CALL_RESULT_SUCCESS",
	2: "RPC_CALL_RESULT_DB_ERROR",
	3: "RPC_CALL_RESULT_INPUT_ERROR",
	4: "RPC_CALL_RESULT_ERROR",
}

var RPC_CALL_RESULT_value = map[string]int32{
	"RPC_CALL_RESULT_NONE":        0,
	"RPC_CALL_RESULT_SUCCESS":     1,
	"RPC_CALL_RESULT_DB_ERROR":    2,
	"RPC_CALL_RESULT_INPUT_ERROR": 3,
	"RPC_CALL_RESULT_ERROR":       4,
}

func (x RPC_CALL_RESULT) String() string {
	return proto.EnumName(RPC_CALL_RESULT_name, int32(x))
}

func (RPC_CALL_RESULT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{0}
}

//消息类型
type MESSAGE_TYPE_RESULT int32

const (
	MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_ALL     MESSAGE_TYPE_RESULT = 0
	MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_SEND    MESSAGE_TYPE_RESULT = 1
	MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_RECEIVE MESSAGE_TYPE_RESULT = 2
)

var MESSAGE_TYPE_RESULT_name = map[int32]string{
	0: "MESSAGE_TYPE_RESULT_ALL",
	1: "MESSAGE_TYPE_RESULT_SEND",
	2: "MESSAGE_TYPE_RESULT_RECEIVE",
}

var MESSAGE_TYPE_RESULT_value = map[string]int32{
	"MESSAGE_TYPE_RESULT_ALL":     0,
	"MESSAGE_TYPE_RESULT_SEND":    1,
	"MESSAGE_TYPE_RESULT_RECEIVE": 2,
}

func (x MESSAGE_TYPE_RESULT) String() string {
	return proto.EnumName(MESSAGE_TYPE_RESULT_name, int32(x))
}

func (MESSAGE_TYPE_RESULT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{1}
}

//阅读状态
type MESSAGE_TYPE_READ int32

const (
	MESSAGE_TYPE_READ_MESSAGE_TYPE_READ_NO  MESSAGE_TYPE_READ = 0
	MESSAGE_TYPE_READ_MESSAGE_TYPE_READ_YES MESSAGE_TYPE_READ = 1
)

var MESSAGE_TYPE_READ_name = map[int32]string{
	0: "MESSAGE_TYPE_READ_NO",
	1: "MESSAGE_TYPE_READ_YES",
}

var MESSAGE_TYPE_READ_value = map[string]int32{
	"MESSAGE_TYPE_READ_NO":  0,
	"MESSAGE_TYPE_READ_YES": 1,
}

func (x MESSAGE_TYPE_READ) String() string {
	return proto.EnumName(MESSAGE_TYPE_READ_name, int32(x))
}

func (MESSAGE_TYPE_READ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{2}
}

//一般rpc调用返回值
type CommonResponse struct {
	Result               RPC_CALL_RESULT `protobuf:"varint,1,opt,name=result,proto3,enum=cfwf.micro_service.activity_review.RPC_CALL_RESULT" json:"result,omitempty"`
	Msg                  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{0}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetResult() RPC_CALL_RESULT {
	if m != nil {
		return m.Result
	}
	return RPC_CALL_RESULT_RPC_CALL_RESULT_NONE
}

func (m *CommonResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type MessageItem struct {
	MessageId            int32               `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	MessageActivityId    int32               `protobuf:"varint,2,opt,name=messageActivityId,proto3" json:"messageActivityId,omitempty"`
	MessageSendId        int64               `protobuf:"varint,3,opt,name=messageSendId,proto3" json:"messageSendId,omitempty"`
	MessageReceiveId     int64               `protobuf:"varint,4,opt,name=messageReceiveId,proto3" json:"messageReceiveId,omitempty"`
	MessageType          MESSAGE_TYPE_RESULT `protobuf:"varint,5,opt,name=messageType,proto3,enum=cfwf.micro_service.activity_review.MESSAGE_TYPE_RESULT" json:"messageType,omitempty"`
	MessageTitle         string              `protobuf:"bytes,6,opt,name=messageTitle,proto3" json:"messageTitle,omitempty"`
	MessageContent       string              `protobuf:"bytes,7,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	MessageTime          int32               `protobuf:"varint,8,opt,name=messageTime,proto3" json:"messageTime,omitempty"`
	MessageIsRead        MESSAGE_TYPE_READ   `protobuf:"varint,9,opt,name=messageIsRead,proto3,enum=cfwf.micro_service.activity_review.MESSAGE_TYPE_READ" json:"messageIsRead,omitempty"`
	MessageReadTime      int32               `protobuf:"varint,10,opt,name=messageReadTime,proto3" json:"messageReadTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MessageItem) Reset()         { *m = MessageItem{} }
func (m *MessageItem) String() string { return proto.CompactTextString(m) }
func (*MessageItem) ProtoMessage()    {}
func (*MessageItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{1}
}

func (m *MessageItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageItem.Unmarshal(m, b)
}
func (m *MessageItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageItem.Marshal(b, m, deterministic)
}
func (m *MessageItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageItem.Merge(m, src)
}
func (m *MessageItem) XXX_Size() int {
	return xxx_messageInfo_MessageItem.Size(m)
}
func (m *MessageItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageItem.DiscardUnknown(m)
}

var xxx_messageInfo_MessageItem proto.InternalMessageInfo

func (m *MessageItem) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *MessageItem) GetMessageActivityId() int32 {
	if m != nil {
		return m.MessageActivityId
	}
	return 0
}

func (m *MessageItem) GetMessageSendId() int64 {
	if m != nil {
		return m.MessageSendId
	}
	return 0
}

func (m *MessageItem) GetMessageReceiveId() int64 {
	if m != nil {
		return m.MessageReceiveId
	}
	return 0
}

func (m *MessageItem) GetMessageType() MESSAGE_TYPE_RESULT {
	if m != nil {
		return m.MessageType
	}
	return MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_ALL
}

func (m *MessageItem) GetMessageTitle() string {
	if m != nil {
		return m.MessageTitle
	}
	return ""
}

func (m *MessageItem) GetMessageContent() string {
	if m != nil {
		return m.MessageContent
	}
	return ""
}

func (m *MessageItem) GetMessageTime() int32 {
	if m != nil {
		return m.MessageTime
	}
	return 0
}

func (m *MessageItem) GetMessageIsRead() MESSAGE_TYPE_READ {
	if m != nil {
		return m.MessageIsRead
	}
	return MESSAGE_TYPE_READ_MESSAGE_TYPE_READ_NO
}

func (m *MessageItem) GetMessageReadTime() int32 {
	if m != nil {
		return m.MessageReadTime
	}
	return 0
}

type CheckItem struct {
	MessageReceiveId     int64             `protobuf:"varint,1,opt,name=messageReceiveId,proto3" json:"messageReceiveId,omitempty"`
	MessageIsRead        MESSAGE_TYPE_READ `protobuf:"varint,2,opt,name=messageIsRead,proto3,enum=cfwf.micro_service.activity_review.MESSAGE_TYPE_READ" json:"messageIsRead,omitempty"`
	MessageReadTime      int32             `protobuf:"varint,3,opt,name=messageReadTime,proto3" json:"messageReadTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CheckItem) Reset()         { *m = CheckItem{} }
func (m *CheckItem) String() string { return proto.CompactTextString(m) }
func (*CheckItem) ProtoMessage()    {}
func (*CheckItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{2}
}

func (m *CheckItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckItem.Unmarshal(m, b)
}
func (m *CheckItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckItem.Marshal(b, m, deterministic)
}
func (m *CheckItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckItem.Merge(m, src)
}
func (m *CheckItem) XXX_Size() int {
	return xxx_messageInfo_CheckItem.Size(m)
}
func (m *CheckItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckItem.DiscardUnknown(m)
}

var xxx_messageInfo_CheckItem proto.InternalMessageInfo

func (m *CheckItem) GetMessageReceiveId() int64 {
	if m != nil {
		return m.MessageReceiveId
	}
	return 0
}

func (m *CheckItem) GetMessageIsRead() MESSAGE_TYPE_READ {
	if m != nil {
		return m.MessageIsRead
	}
	return MESSAGE_TYPE_READ_MESSAGE_TYPE_READ_NO
}

func (m *CheckItem) GetMessageReadTime() int32 {
	if m != nil {
		return m.MessageReadTime
	}
	return 0
}

//发送消息通知-Request
type SendActivityReviewMessageRequest struct {
	//Required
	MessageActivityId int32               `protobuf:"varint,1,opt,name=messageActivityId,proto3" json:"messageActivityId,omitempty"`
	MessageSendId     int64               `protobuf:"varint,2,opt,name=messageSendId,proto3" json:"messageSendId,omitempty"`
	MessageReceiveId  []int64             `protobuf:"varint,3,rep,packed,name=messageReceiveId,proto3" json:"messageReceiveId,omitempty"`
	MessageType       MESSAGE_TYPE_RESULT `protobuf:"varint,4,opt,name=messageType,proto3,enum=cfwf.micro_service.activity_review.MESSAGE_TYPE_RESULT" json:"messageType,omitempty"`
	MessageTitle      string              `protobuf:"bytes,5,opt,name=messageTitle,proto3" json:"messageTitle,omitempty"`
	MessageContent    string              `protobuf:"bytes,6,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	MessageTime       int32               `protobuf:"varint,7,opt,name=messageTime,proto3" json:"messageTime,omitempty"`
	//Optional
	MessageParentId      int32    `protobuf:"varint,8,opt,name=messageParentId,proto3" json:"messageParentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendActivityReviewMessageRequest) Reset()         { *m = SendActivityReviewMessageRequest{} }
func (m *SendActivityReviewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendActivityReviewMessageRequest) ProtoMessage()    {}
func (*SendActivityReviewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{3}
}

func (m *SendActivityReviewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendActivityReviewMessageRequest.Unmarshal(m, b)
}
func (m *SendActivityReviewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendActivityReviewMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendActivityReviewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendActivityReviewMessageRequest.Merge(m, src)
}
func (m *SendActivityReviewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendActivityReviewMessageRequest.Size(m)
}
func (m *SendActivityReviewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendActivityReviewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendActivityReviewMessageRequest proto.InternalMessageInfo

func (m *SendActivityReviewMessageRequest) GetMessageActivityId() int32 {
	if m != nil {
		return m.MessageActivityId
	}
	return 0
}

func (m *SendActivityReviewMessageRequest) GetMessageSendId() int64 {
	if m != nil {
		return m.MessageSendId
	}
	return 0
}

func (m *SendActivityReviewMessageRequest) GetMessageReceiveId() []int64 {
	if m != nil {
		return m.MessageReceiveId
	}
	return nil
}

func (m *SendActivityReviewMessageRequest) GetMessageType() MESSAGE_TYPE_RESULT {
	if m != nil {
		return m.MessageType
	}
	return MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_ALL
}

func (m *SendActivityReviewMessageRequest) GetMessageTitle() string {
	if m != nil {
		return m.MessageTitle
	}
	return ""
}

func (m *SendActivityReviewMessageRequest) GetMessageContent() string {
	if m != nil {
		return m.MessageContent
	}
	return ""
}

func (m *SendActivityReviewMessageRequest) GetMessageTime() int32 {
	if m != nil {
		return m.MessageTime
	}
	return 0
}

func (m *SendActivityReviewMessageRequest) GetMessageParentId() int32 {
	if m != nil {
		return m.MessageParentId
	}
	return 0
}

//获取消息通知-Request
type GetActivityReviewMessageRequest struct {
	//Required
	MessageReceiveId int64               `protobuf:"varint,1,opt,name=messageReceiveId,proto3" json:"messageReceiveId,omitempty"`
	MessageType      MESSAGE_TYPE_RESULT `protobuf:"varint,2,opt,name=messageType,proto3,enum=cfwf.micro_service.activity_review.MESSAGE_TYPE_RESULT" json:"messageType,omitempty"`
	//Optional
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivityReviewMessageRequest) Reset()         { *m = GetActivityReviewMessageRequest{} }
func (m *GetActivityReviewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetActivityReviewMessageRequest) ProtoMessage()    {}
func (*GetActivityReviewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{4}
}

func (m *GetActivityReviewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityReviewMessageRequest.Unmarshal(m, b)
}
func (m *GetActivityReviewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityReviewMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetActivityReviewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityReviewMessageRequest.Merge(m, src)
}
func (m *GetActivityReviewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetActivityReviewMessageRequest.Size(m)
}
func (m *GetActivityReviewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityReviewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityReviewMessageRequest proto.InternalMessageInfo

func (m *GetActivityReviewMessageRequest) GetMessageReceiveId() int64 {
	if m != nil {
		return m.MessageReceiveId
	}
	return 0
}

func (m *GetActivityReviewMessageRequest) GetMessageType() MESSAGE_TYPE_RESULT {
	if m != nil {
		return m.MessageType
	}
	return MESSAGE_TYPE_RESULT_MESSAGE_TYPE_RESULT_ALL
}

func (m *GetActivityReviewMessageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetActivityReviewMessageRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//获取消息通知-Response
type GetActivityReviewMessageResponse struct {
	Result               RPC_CALL_RESULT `protobuf:"varint,1,opt,name=result,proto3,enum=cfwf.micro_service.activity_review.RPC_CALL_RESULT" json:"result,omitempty"`
	MaxCount             int32           `protobuf:"varint,2,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	NoReadCount          int32           `protobuf:"varint,3,opt,name=noReadCount,proto3" json:"noReadCount,omitempty"`
	List                 []*MessageItem  `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetActivityReviewMessageResponse) Reset()         { *m = GetActivityReviewMessageResponse{} }
func (m *GetActivityReviewMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GetActivityReviewMessageResponse) ProtoMessage()    {}
func (*GetActivityReviewMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{5}
}

func (m *GetActivityReviewMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivityReviewMessageResponse.Unmarshal(m, b)
}
func (m *GetActivityReviewMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivityReviewMessageResponse.Marshal(b, m, deterministic)
}
func (m *GetActivityReviewMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivityReviewMessageResponse.Merge(m, src)
}
func (m *GetActivityReviewMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GetActivityReviewMessageResponse.Size(m)
}
func (m *GetActivityReviewMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivityReviewMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivityReviewMessageResponse proto.InternalMessageInfo

func (m *GetActivityReviewMessageResponse) GetResult() RPC_CALL_RESULT {
	if m != nil {
		return m.Result
	}
	return RPC_CALL_RESULT_RPC_CALL_RESULT_NONE
}

func (m *GetActivityReviewMessageResponse) GetMaxCount() int32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *GetActivityReviewMessageResponse) GetNoReadCount() int32 {
	if m != nil {
		return m.NoReadCount
	}
	return 0
}

func (m *GetActivityReviewMessageResponse) GetList() []*MessageItem {
	if m != nil {
		return m.List
	}
	return nil
}

//阅读消息通知-Request
type ReadActivityReviewMessageRequest struct {
	//Required
	MessageId            int32    `protobuf:"varint,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadActivityReviewMessageRequest) Reset()         { *m = ReadActivityReviewMessageRequest{} }
func (m *ReadActivityReviewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ReadActivityReviewMessageRequest) ProtoMessage()    {}
func (*ReadActivityReviewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{6}
}

func (m *ReadActivityReviewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadActivityReviewMessageRequest.Unmarshal(m, b)
}
func (m *ReadActivityReviewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadActivityReviewMessageRequest.Marshal(b, m, deterministic)
}
func (m *ReadActivityReviewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadActivityReviewMessageRequest.Merge(m, src)
}
func (m *ReadActivityReviewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_ReadActivityReviewMessageRequest.Size(m)
}
func (m *ReadActivityReviewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadActivityReviewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadActivityReviewMessageRequest proto.InternalMessageInfo

func (m *ReadActivityReviewMessageRequest) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

//消息查阅情况-Request
type CheckActivityReviewMessageRequest struct {
	//Required
	MessageParentId int32 `protobuf:"varint,1,opt,name=messageParentId,proto3" json:"messageParentId,omitempty"`
	//Optional
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckActivityReviewMessageRequest) Reset()         { *m = CheckActivityReviewMessageRequest{} }
func (m *CheckActivityReviewMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CheckActivityReviewMessageRequest) ProtoMessage()    {}
func (*CheckActivityReviewMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{7}
}

func (m *CheckActivityReviewMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckActivityReviewMessageRequest.Unmarshal(m, b)
}
func (m *CheckActivityReviewMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckActivityReviewMessageRequest.Marshal(b, m, deterministic)
}
func (m *CheckActivityReviewMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckActivityReviewMessageRequest.Merge(m, src)
}
func (m *CheckActivityReviewMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CheckActivityReviewMessageRequest.Size(m)
}
func (m *CheckActivityReviewMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckActivityReviewMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckActivityReviewMessageRequest proto.InternalMessageInfo

func (m *CheckActivityReviewMessageRequest) GetMessageParentId() int32 {
	if m != nil {
		return m.MessageParentId
	}
	return 0
}

func (m *CheckActivityReviewMessageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *CheckActivityReviewMessageRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

//消息查阅情况-Response
type CheckActivityReviewMessageResponse struct {
	Result               RPC_CALL_RESULT `protobuf:"varint,1,opt,name=result,proto3,enum=cfwf.micro_service.activity_review.RPC_CALL_RESULT" json:"result,omitempty"`
	MaxCount             int32           `protobuf:"varint,2,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	MessageTime          int32           `protobuf:"varint,3,opt,name=messageTime,proto3" json:"messageTime,omitempty"`
	MessageReceiveId     []int64         `protobuf:"varint,4,rep,packed,name=messageReceiveId,proto3" json:"messageReceiveId,omitempty"`
	List                 []*CheckItem    `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CheckActivityReviewMessageResponse) Reset()         { *m = CheckActivityReviewMessageResponse{} }
func (m *CheckActivityReviewMessageResponse) String() string { return proto.CompactTextString(m) }
func (*CheckActivityReviewMessageResponse) ProtoMessage()    {}
func (*CheckActivityReviewMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1f60e866858d4b1, []int{8}
}

func (m *CheckActivityReviewMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckActivityReviewMessageResponse.Unmarshal(m, b)
}
func (m *CheckActivityReviewMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckActivityReviewMessageResponse.Marshal(b, m, deterministic)
}
func (m *CheckActivityReviewMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckActivityReviewMessageResponse.Merge(m, src)
}
func (m *CheckActivityReviewMessageResponse) XXX_Size() int {
	return xxx_messageInfo_CheckActivityReviewMessageResponse.Size(m)
}
func (m *CheckActivityReviewMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckActivityReviewMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckActivityReviewMessageResponse proto.InternalMessageInfo

func (m *CheckActivityReviewMessageResponse) GetResult() RPC_CALL_RESULT {
	if m != nil {
		return m.Result
	}
	return RPC_CALL_RESULT_RPC_CALL_RESULT_NONE
}

func (m *CheckActivityReviewMessageResponse) GetMaxCount() int32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

func (m *CheckActivityReviewMessageResponse) GetMessageTime() int32 {
	if m != nil {
		return m.MessageTime
	}
	return 0
}

func (m *CheckActivityReviewMessageResponse) GetMessageReceiveId() []int64 {
	if m != nil {
		return m.MessageReceiveId
	}
	return nil
}

func (m *CheckActivityReviewMessageResponse) GetList() []*CheckItem {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("cfwf.micro_service.activity_review.RPC_CALL_RESULT", RPC_CALL_RESULT_name, RPC_CALL_RESULT_value)
	proto.RegisterEnum("cfwf.micro_service.activity_review.MESSAGE_TYPE_RESULT", MESSAGE_TYPE_RESULT_name, MESSAGE_TYPE_RESULT_value)
	proto.RegisterEnum("cfwf.micro_service.activity_review.MESSAGE_TYPE_READ", MESSAGE_TYPE_READ_name, MESSAGE_TYPE_READ_value)
	proto.RegisterType((*CommonResponse)(nil), "cfwf.micro_service.activity_review.CommonResponse")
	proto.RegisterType((*MessageItem)(nil), "cfwf.micro_service.activity_review.MessageItem")
	proto.RegisterType((*CheckItem)(nil), "cfwf.micro_service.activity_review.CheckItem")
	proto.RegisterType((*SendActivityReviewMessageRequest)(nil), "cfwf.micro_service.activity_review.SendActivityReviewMessageRequest")
	proto.RegisterType((*GetActivityReviewMessageRequest)(nil), "cfwf.micro_service.activity_review.GetActivityReviewMessageRequest")
	proto.RegisterType((*GetActivityReviewMessageResponse)(nil), "cfwf.micro_service.activity_review.GetActivityReviewMessageResponse")
	proto.RegisterType((*ReadActivityReviewMessageRequest)(nil), "cfwf.micro_service.activity_review.ReadActivityReviewMessageRequest")
	proto.RegisterType((*CheckActivityReviewMessageRequest)(nil), "cfwf.micro_service.activity_review.CheckActivityReviewMessageRequest")
	proto.RegisterType((*CheckActivityReviewMessageResponse)(nil), "cfwf.micro_service.activity_review.CheckActivityReviewMessageResponse")
}

func init() { proto.RegisterFile("activity_review.proto", fileDescriptor_d1f60e866858d4b1) }

var fileDescriptor_d1f60e866858d4b1 = []byte{
	// 827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xce, 0xd8, 0x49, 0x20, 0x87, 0x7b, 0x83, 0x99, 0x7b, 0xd1, 0x35, 0x01, 0x09, 0x5f, 0xab,
	0x42, 0x51, 0xd4, 0xa6, 0x52, 0x50, 0xd5, 0x6d, 0x83, 0xe3, 0xd2, 0xa8, 0x21, 0x44, 0xe3, 0x50,
	0x09, 0x75, 0x61, 0xa5, 0xc9, 0x40, 0xad, 0x62, 0x3b, 0xc4, 0x26, 0x94, 0x4a, 0x7d, 0x8c, 0xaa,
	0x3b, 0x16, 0xdd, 0x74, 0xd5, 0x57, 0xe8, 0x73, 0xf4, 0x39, 0xba, 0xed, 0xa6, 0xf2, 0xc4, 0xf9,
	0xb3, 0x9d, 0xc4, 0x85, 0xa2, 0xae, 0xf0, 0x7c, 0x67, 0x38, 0x73, 0xce, 0xf7, 0x7d, 0x73, 0x06,
	0x60, 0xbd, 0xd5, 0x76, 0x8d, 0xbe, 0xe1, 0x5e, 0xe9, 0x3d, 0xda, 0x37, 0xe8, 0x65, 0xb1, 0xdb,
	0xb3, 0x5d, 0x1b, 0xcb, 0xed, 0x93, 0xcb, 0x93, 0xa2, 0x69, 0xb4, 0x7b, 0xb6, 0xee, 0xd0, 0x5e,
	0xdf, 0x68, 0xd3, 0x62, 0x60, 0xa7, 0x6c, 0x43, 0x56, 0xb1, 0x4d, 0xd3, 0xb6, 0x08, 0x75, 0xba,
	0xb6, 0xe5, 0x50, 0xfc, 0x1c, 0xd2, 0x3d, 0xea, 0x5c, 0x9c, 0xb9, 0x22, 0x92, 0x50, 0x3e, 0x5b,
	0xda, 0x2d, 0x2e, 0x4e, 0x53, 0x24, 0x0d, 0x45, 0x57, 0xca, 0xb5, 0x9a, 0x4e, 0x54, 0xed, 0xa8,
	0xd6, 0x24, 0x7e, 0x0a, 0x2c, 0x00, 0x6f, 0x3a, 0xa7, 0x22, 0x27, 0xa1, 0x7c, 0x86, 0x78, 0x9f,
	0xf2, 0x0f, 0x1e, 0x56, 0x0e, 0xa8, 0xe3, 0xb4, 0x4e, 0x69, 0xd5, 0xa5, 0x26, 0xde, 0x82, 0x8c,
	0xe9, 0x2f, 0x3b, 0xec, 0xc4, 0x14, 0x19, 0x03, 0xf8, 0x3e, 0xac, 0xf9, 0x8b, 0xb2, 0x7f, 0x62,
	0xb5, 0xc3, 0xb2, 0xa5, 0x48, 0x38, 0x80, 0xef, 0xc1, 0xdf, 0x3e, 0xa8, 0x51, 0xab, 0x53, 0xed,
	0x88, 0xbc, 0x84, 0xf2, 0x3c, 0x99, 0x06, 0x71, 0x01, 0x04, 0x1f, 0x20, 0xb4, 0x4d, 0x8d, 0xbe,
	0x77, 0x70, 0x92, 0x6d, 0x0c, 0xe1, 0xf8, 0x18, 0x56, 0x7c, 0xac, 0x79, 0xd5, 0xa5, 0x62, 0x8a,
	0x31, 0xf2, 0x38, 0x0e, 0x23, 0x07, 0xaa, 0xa6, 0x95, 0xf7, 0x55, 0xbd, 0x79, 0xdc, 0x50, 0x87,
	0xac, 0x4c, 0xe6, 0xc2, 0x32, 0xfc, 0x35, 0x5c, 0x1a, 0xee, 0x19, 0x15, 0xd3, 0x8c, 0xa3, 0x29,
	0x0c, 0xef, 0x40, 0xd6, 0x5f, 0x2b, 0xb6, 0xe5, 0x52, 0xcb, 0x15, 0x97, 0xd8, 0xae, 0x00, 0x8a,
	0xa5, 0x71, 0x99, 0x86, 0x49, 0xc5, 0x65, 0x46, 0xd0, 0x24, 0x84, 0x5f, 0x8e, 0xa8, 0xa9, 0x3a,
	0x84, 0xb6, 0x3a, 0x62, 0x86, 0xb5, 0xf2, 0xe8, 0x06, 0xad, 0x94, 0x2b, 0x64, 0x3a, 0x17, 0xce,
	0xc3, 0xea, 0x88, 0xb9, 0x56, 0x87, 0x95, 0x00, 0xac, 0x84, 0x20, 0x2c, 0x7f, 0x45, 0x90, 0x51,
	0x5e, 0xd3, 0xf6, 0x1b, 0xa6, 0x7d, 0x94, 0x12, 0x68, 0x86, 0x12, 0xa1, 0x06, 0xb8, 0xbb, 0x6d,
	0x80, 0x8f, 0x6e, 0xe0, 0x03, 0x0f, 0x92, 0xe7, 0xa3, 0xa1, 0xeb, 0x08, 0x3b, 0xe1, 0x60, 0xb8,
	0xeb, 0xfc, 0x82, 0x3a, 0x6e, 0xb4, 0x6b, 0x51, 0x6c, 0xd7, 0x72, 0x71, 0x5d, 0xcb, 0x4b, 0x7c,
	0x1c, 0xd7, 0x26, 0xef, 0xd0, 0xb5, 0xa9, 0x58, 0xae, 0x4d, 0xc7, 0x71, 0xed, 0x52, 0xd8, 0xb5,
	0x63, 0x5d, 0x1a, 0xad, 0x1e, 0xb5, 0xdc, 0x6a, 0xc7, 0xf7, 0x76, 0x10, 0x96, 0xbf, 0x21, 0xd8,
	0xde, 0xa7, 0xee, 0x5c, 0x59, 0x7e, 0xc5, 0x6e, 0x01, 0x0a, 0xb9, 0xdf, 0x48, 0x21, 0x86, 0x64,
	0xb7, 0x75, 0x3a, 0x74, 0x18, 0xfb, 0xc6, 0x39, 0x58, 0xf6, 0x7e, 0x6a, 0xc6, 0xbb, 0x81, 0x5c,
	0x29, 0x32, 0x5a, 0xcb, 0xdf, 0x11, 0x48, 0xb3, 0x5b, 0xbb, 0x8b, 0xa9, 0x9d, 0x83, 0x65, 0xb3,
	0xf5, 0x56, 0xb1, 0x2f, 0x2c, 0xd7, 0x1f, 0xb6, 0xa3, 0xb5, 0x27, 0x9a, 0x65, 0x7b, 0xd7, 0x61,
	0x10, 0x1e, 0x34, 0x31, 0x09, 0x61, 0x05, 0x92, 0x67, 0x86, 0xe3, 0x8a, 0x49, 0x89, 0xcf, 0xaf,
	0x94, 0x1e, 0xc6, 0xe2, 0x6c, 0xfc, 0x20, 0x10, 0xf6, 0xcb, 0xf2, 0x13, 0x90, 0xbc, 0x8c, 0x73,
	0xf5, 0x9c, 0xfb, 0x74, 0xc8, 0xef, 0xe1, 0x7f, 0x36, 0x69, 0xe6, 0xa6, 0x88, 0x30, 0x18, 0x8a,
	0x34, 0xd8, 0x48, 0x35, 0x6e, 0x86, 0x6a, 0x7c, 0x40, 0xb5, 0x6b, 0x0e, 0xe4, 0x79, 0xe7, 0xff,
	0x01, 0xdd, 0x26, 0x2f, 0x1b, 0x1f, 0xbe, 0x6c, 0xd1, 0xef, 0x62, 0xf4, 0x84, 0x29, 0xfb, 0x1a,
	0xa7, 0x98, 0xc6, 0x0f, 0xe2, 0x14, 0x3d, 0x1a, 0xfb, 0x03, 0x85, 0x0b, 0x9f, 0x10, 0xac, 0x06,
	0x1a, 0xc1, 0x22, 0xfc, 0x1b, 0x80, 0xf4, 0xfa, 0x61, 0x5d, 0x15, 0x12, 0x78, 0x13, 0xfe, 0x0b,
	0x46, 0xb4, 0x23, 0x45, 0x51, 0x35, 0x4d, 0x40, 0x78, 0x0b, 0xc4, 0x60, 0xb0, 0xb2, 0xa7, 0xab,
	0x84, 0x1c, 0x12, 0x81, 0xc3, 0xdb, 0xb0, 0x19, 0x8c, 0x56, 0xeb, 0x8d, 0xa3, 0xa6, 0xbf, 0x81,
	0xc7, 0x1b, 0xb0, 0x1e, 0xdc, 0x30, 0x08, 0x25, 0x0b, 0xe7, 0xf0, 0x4f, 0xc4, 0x7d, 0xf6, 0xaa,
	0x89, 0x80, 0xf5, 0x72, 0xad, 0x26, 0x24, 0xbc, 0x6a, 0xa2, 0x82, 0x9a, 0x5a, 0xaf, 0x08, 0xc8,
	0xab, 0x26, 0x2a, 0x4a, 0x54, 0x45, 0xad, 0xbe, 0x50, 0x05, 0xae, 0xf0, 0x0c, 0xd6, 0x42, 0xef,
	0x95, 0x47, 0x4c, 0x08, 0xd4, 0xeb, 0x87, 0x42, 0xc2, 0x2b, 0x3e, 0x1c, 0x39, 0x56, 0x35, 0x01,
	0x95, 0xae, 0x53, 0x90, 0x9d, 0x76, 0x1f, 0xfe, 0x88, 0x60, 0x63, 0xe6, 0xf3, 0x85, 0x2b, 0x71,
	0x74, 0x5c, 0xf4, 0xfa, 0xe5, 0x4a, 0xb1, 0xdc, 0x30, 0xf5, 0x47, 0xa7, 0x9c, 0xc0, 0x9f, 0x11,
	0x88, 0xb3, 0xa6, 0x1c, 0x56, 0xe2, 0xa4, 0x5c, 0x30, 0xfe, 0x73, 0x95, 0xdb, 0x25, 0x19, 0x55,
	0xea, 0x71, 0x38, 0x73, 0x36, 0xc5, 0xe3, 0x70, 0xd1, 0x68, 0xbb, 0x21, 0x87, 0x5f, 0x10, 0xe4,
	0x66, 0xcf, 0x1c, 0xac, 0xc6, 0xbe, 0xa6, 0x73, 0x6b, 0x7b, 0x7a, 0xdb, 0x34, 0xc3, 0x7a, 0xf7,
	0xf2, 0xb0, 0xd3, 0xb6, 0xcd, 0x18, 0xe9, 0x5e, 0xa5, 0xd9, 0x7f, 0x34, 0xbb, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x24, 0x93, 0x54, 0xb4, 0xea, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActivityReviewClient is the client API for ActivityReview service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActivityReviewClient interface {
	//发送消息通知
	SendActivityReviewMessage(ctx context.Context, in *SendActivityReviewMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	//获取消息通知
	GetActivityReviewMessage(ctx context.Context, in *GetActivityReviewMessageRequest, opts ...grpc.CallOption) (*GetActivityReviewMessageResponse, error)
	//阅读消息通知
	ReadActivityReviewMessage(ctx context.Context, in *ReadActivityReviewMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error)
	//消息查阅情况
	CheckActivityReviewMessage(ctx context.Context, in *CheckActivityReviewMessageRequest, opts ...grpc.CallOption) (*CheckActivityReviewMessageResponse, error)
}

type activityReviewClient struct {
	cc *grpc.ClientConn
}

func NewActivityReviewClient(cc *grpc.ClientConn) ActivityReviewClient {
	return &activityReviewClient{cc}
}

func (c *activityReviewClient) SendActivityReviewMessage(ctx context.Context, in *SendActivityReviewMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/cfwf.micro_service.activity_review.ActivityReview/SendActivityReviewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityReviewClient) GetActivityReviewMessage(ctx context.Context, in *GetActivityReviewMessageRequest, opts ...grpc.CallOption) (*GetActivityReviewMessageResponse, error) {
	out := new(GetActivityReviewMessageResponse)
	err := c.cc.Invoke(ctx, "/cfwf.micro_service.activity_review.ActivityReview/GetActivityReviewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityReviewClient) ReadActivityReviewMessage(ctx context.Context, in *ReadActivityReviewMessageRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/cfwf.micro_service.activity_review.ActivityReview/ReadActivityReviewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityReviewClient) CheckActivityReviewMessage(ctx context.Context, in *CheckActivityReviewMessageRequest, opts ...grpc.CallOption) (*CheckActivityReviewMessageResponse, error) {
	out := new(CheckActivityReviewMessageResponse)
	err := c.cc.Invoke(ctx, "/cfwf.micro_service.activity_review.ActivityReview/CheckActivityReviewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityReviewServer is the server API for ActivityReview service.
type ActivityReviewServer interface {
	//发送消息通知
	SendActivityReviewMessage(context.Context, *SendActivityReviewMessageRequest) (*CommonResponse, error)
	//获取消息通知
	GetActivityReviewMessage(context.Context, *GetActivityReviewMessageRequest) (*GetActivityReviewMessageResponse, error)
	//阅读消息通知
	ReadActivityReviewMessage(context.Context, *ReadActivityReviewMessageRequest) (*CommonResponse, error)
	//消息查阅情况
	CheckActivityReviewMessage(context.Context, *CheckActivityReviewMessageRequest) (*CheckActivityReviewMessageResponse, error)
}

func RegisterActivityReviewServer(s *grpc.Server, srv ActivityReviewServer) {
	s.RegisterService(&_ActivityReview_serviceDesc, srv)
}

func _ActivityReview_SendActivityReviewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActivityReviewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityReviewServer).SendActivityReviewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfwf.micro_service.activity_review.ActivityReview/SendActivityReviewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityReviewServer).SendActivityReviewMessage(ctx, req.(*SendActivityReviewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityReview_GetActivityReviewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityReviewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityReviewServer).GetActivityReviewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfwf.micro_service.activity_review.ActivityReview/GetActivityReviewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityReviewServer).GetActivityReviewMessage(ctx, req.(*GetActivityReviewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityReview_ReadActivityReviewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadActivityReviewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityReviewServer).ReadActivityReviewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfwf.micro_service.activity_review.ActivityReview/ReadActivityReviewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityReviewServer).ReadActivityReviewMessage(ctx, req.(*ReadActivityReviewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityReview_CheckActivityReviewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckActivityReviewMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityReviewServer).CheckActivityReviewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cfwf.micro_service.activity_review.ActivityReview/CheckActivityReviewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityReviewServer).CheckActivityReviewMessage(ctx, req.(*CheckActivityReviewMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ActivityReview_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cfwf.micro_service.activity_review.ActivityReview",
	HandlerType: (*ActivityReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendActivityReviewMessage",
			Handler:    _ActivityReview_SendActivityReviewMessage_Handler,
		},
		{
			MethodName: "GetActivityReviewMessage",
			Handler:    _ActivityReview_GetActivityReviewMessage_Handler,
		},
		{
			MethodName: "ReadActivityReviewMessage",
			Handler:    _ActivityReview_ReadActivityReviewMessage_Handler,
		},
		{
			MethodName: "CheckActivityReviewMessage",
			Handler:    _ActivityReview_CheckActivityReviewMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "activity_review.proto",
}
